# Stochastic Gradient Descent

## SGD Classifier

In [1]:
import numpy as np
from sklearn import linear_model
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
Y = np.array([1, 1, 2, 2])
SGDClf = linear_model.SGDClassifier(max_iter=1000, tol=1e3,penalty="elasticnet")
SGDClf.fit(X, Y)


SGDClassifier(penalty='elasticnet', tol=1000.0)

In [2]:
SGDClf.predict([[2.,2.]])

array([2])

In [3]:
SGDClf.coef_


array([[9.80505936, 9.80505936]])

In [4]:
SGDClf.intercept_


array([-10.])

In [5]:
SGDClf.decision_function([[2., 2.]])

array([29.22023745])

## SGD Regressor

In [8]:
import numpy as np
from sklearn import linear_model

n_samples, n_features = 10, 5
rng = np.random.RandomState(0)

y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)

SGDReg =linear_model.SGDRegressor(max_iter=1000,penalty="elasticnet",loss='huber',tol=1e-3, average=True)
SGDReg.fit(X, y)


SGDRegressor(average=True, loss='huber', penalty='elasticnet')

In [9]:
SGDReg.coef_

array([-0.00529979,  0.00333286, -0.00383609,  0.00563213,  0.00518263])

In [11]:
SGDReg.intercept_

array([0.00655439])

In [12]:
SGDReg.t_

61.0