## Linear Regression

In [16]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1,1],[1,2],[2,2],[2,3]])
y = np.dot(X, np.array([1,2])) + 3

regr = LinearRegression(fit_intercept=True, normalize = True, copy_X=True,
n_jobs=2).fit(X,y)

regr.predict(np.array([[3,5]]))
regr.score(X,y)
regr.coef_
regr.intercept_

3.0000000000000018

## Logistic Regression

In [25]:
from sklearn import datasets
from sklearn import linear_model
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)

#LRG = LogisticRegression(random_state=0, solver='liblinear', multiclass='auto').fit(X, y)

LRG = linear_model.LogisticRegression(random_state=0, solver='liblinear').fit(X, y)
LRG.score(X, y)

0.96

## Ridge Regression

In [28]:
from sklearn.linear_model import Ridge
import numpy as np
n_samples, n_features = 15, 10
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)
rdg = Ridge(alpha=0.5)
rdg.fit(X, y)
rdg.score(X,y)


0.7629498741931634

In [29]:
rdg.coef_


array([ 0.32720254, -0.34503436, -0.2913278 ,  0.2693125 , -0.22832508,
       -0.8635094 , -0.17079403, -0.36288055, -0.17241081, -0.43136046])

In [30]:
rdg.intercept_

0.5274865723969377

## Bayesian Ridge Regression

In [32]:
from sklearn import linear_model
X = [[0, 0], [1, 1], [2, 2], [3, 3]]
Y = [0, 1, 2, 3]
BayReg = linear_model.BayesianRidge()
BayReg.fit(X, Y)

BayesianRidge()

In [33]:
BayReg.predict([[1,1]])

array([1.00000007])

In [34]:
BayReg.coef_

array([0.49999993, 0.49999993])

## LASSO (Least Absolute Shrinkage and Selection Operator)

In [35]:
from sklearn import linear_model
Lreg = linear_model.Lasso(alpha=0.5)
Lreg.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])

Lasso(alpha=0.5)

In [36]:
Lreg.predict([[0,1]])

array([0.75])

In [37]:
Lreg.coef_

array([0.25, 0.  ])

In [38]:
Lreg.intercept_

0.75

In [39]:
Lreg.n_iter_

2

## Multi-task LASSO

In [40]:
from sklearn import linear_model
MTLReg = linear_model.MultiTaskLasso(alpha=0.5)
MTLReg.fit([[0,0], [1, 1], [2, 2]], [[0, 0],[1,1],[2,2]])

MultiTaskLasso(alpha=0.5)

In [41]:
MTLReg.predict([[0,1]])

array([[0.53033009, 0.53033009]])

In [43]:
MTLReg.coef_

array([[4.69669914e-01, 1.76635402e-16],
       [4.69669914e-01, 1.76635402e-16]])

In [44]:
MTLReg.intercept_

array([0.53033009, 0.53033009])

In [45]:
MTLReg.n_iter_

2

## Elastic-Net

In [49]:
from sklearn import linear_model
ENreg = linear_model.ElasticNet(alpha=0.5,random_state=0)
ENreg.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])

ElasticNet(alpha=0.5, random_state=0)

In [51]:
ENreg.predict([[0,1]]) 

array([0.73681643])

In [52]:
ENreg.coef_

array([0.26318357, 0.26313923])

In [53]:
ENreg.intercept_

0.47367720941913904

In [54]:
ENreg.n_iter_

15

## MultiTaskElasticNet

In [55]:
from sklearn import linear_model
MTENReg = linear_model.MultiTaskElasticNet(alpha=0.5)
MTENReg.fit([[0,0], [1, 1], [2, 2]], [[0, 0],[1,1],[2,2]])

MultiTaskElasticNet(alpha=0.5)

In [56]:
MTENReg.predict([[1,0]])

array([[0.69061776, 0.69061776]])

In [61]:
MTENReg.coef_

array([[0.30943437, 0.30938224],
       [0.30943437, 0.30938224]])

In [60]:
MTENReg.intercept_

array([0.38118338, 0.38118338])

In [59]:
MTENReg.n_iter_

15